default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blogapp_development
  username: postgres
  password: samif

test:
  <<: *default
  database: blogapp_test
  username: postgres
  password: samif

production:
  <<: *default
  database: blogapp_production
  username: postgres
  password: samif
